# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/consta_m/Projet/YAOSGUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/consta_m/Projet/YAOSGUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/consta_m/Projet/YAOSGUI/CMakeFiles /home/consta_m/Projet/YAOSGUI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/consta_m/Projet/YAOSGUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named YAOSGUI

# Build rule for target.
YAOSGUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 YAOSGUI
.PHONY : YAOSGUI

# fast build rule for target.
YAOSGUI/fast:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/build
.PHONY : YAOSGUI/fast

src/Button.o: src/Button.cpp.o
.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i
.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s
.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/DesignButton.o: src/DesignButton.cpp.o
.PHONY : src/DesignButton.o

# target to build an object file
src/DesignButton.cpp.o:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/DesignButton.cpp.o
.PHONY : src/DesignButton.cpp.o

src/DesignButton.i: src/DesignButton.cpp.i
.PHONY : src/DesignButton.i

# target to preprocess a source file
src/DesignButton.cpp.i:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/DesignButton.cpp.i
.PHONY : src/DesignButton.cpp.i

src/DesignButton.s: src/DesignButton.cpp.s
.PHONY : src/DesignButton.s

# target to generate assembly for a file
src/DesignButton.cpp.s:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/DesignButton.cpp.s
.PHONY : src/DesignButton.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/YAOSGUI.dir/build.make CMakeFiles/YAOSGUI.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... YAOSGUI"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/DesignButton.o"
	@echo "... src/DesignButton.i"
	@echo "... src/DesignButton.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

